### ISSUE TITLE
项目启动失败

### ISSUE THREAD

**Issue by wancheng** [vvandk/kinit#11]
启动项目遇到问题，日志如下：

```
开始初始化数据
online
Traceback (most recent call last):
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/alembic/command.py", line 229, in revision
    script_directory.run_env()
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/wanchengzhang/Programming/python/kinit/kinit-api/alembic/env.py", line 89, in <module>
    run_migrations_online()
  File "/Users/wanchengzhang/Programming/python/kinit/kinit-api/alembic/env.py", line 69, in run_migrations_online
    connectable = engine_from_config(
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 803, in engine_from_config
    return create_engine(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/sqlalchemy/engine/url.py", line 838, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/site-packages/sqlalchemy/engine/url.py", line 899, in _parse_url
    components["port"] = int(components["port"])
                         ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'post'
Traceback (most recent call last):

  File "/Users/wanchengzhang/Programming/python/kinit/kinit-api/main.py", line 118, in <module>
    shell_app()

  File "/Users/wanchengzhang/Programming/python/kinit/kinit-api/main.py", line 91, in init
    asyncio.run(data.run(env))

  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "/Users/wanchengzhang/Programming/python/kinit/kinit-api/scripts/initialize/initialize.py", line 155, in run
    self.migrate_model(env)

  File "/Users/wanchengzhang/Programming/python/kinit/kinit-api/scripts/initialize/initialize.py", line 51, in migrate_model
    subprocess.check_call(['alembic', '--name', f'{env.value}', 'revision', '--autogenerate', '-m', f'{VERSION}'], cwd=BASE_DIR)

  File "/Users/wanchengzhang/.pyenv/versions/3.11.1/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['alembic', '--name', 'dev', 'revision', '--autogenerate', '-m', '2.3.0']' returned non-zero exit status 1.
```

**Comment by vvandk** [comment]
重新执行初始化项目时，需要清理数据库并且清理已生成的数据库迁移文件：kinit-api/alembic/versions_dev

开发环境下初始化项目需要将 application/settings.py:DEBUG 改为True后在执行

**Comment by wancheng** [comment]
`rm -rf kinit-api/alembic/versions_dev/*.py`

重新执行，成功了。
