### ISSUE TITLE
执行 初始化数据库数据  python3 main.py init --env dev时报错

### ISSUE THREAD

**Issue by rio196649** [vvandk/kinit#2]
Traceback (most recent call last):
  File "/Volumes/DATA/Projects/pterosaur/main.py", line 18, in <module>
    from application import urls
  File "/Volumes/DATA/Projects/pterosaur/application/urls.py", line 8, in <module>
    from apps import *
  File "/Volumes/DATA/Projects/pterosaur/apps/__init__.py", line 10, in <module>
    from apps.vadmin.auth.utils.login import app as auth_app
  File "/Volumes/DATA/Projects/pterosaur/apps/vadmin/auth/utils/login.py", line 30, in <module>
    from .login_manage import LoginManage
  File "/Volumes/DATA/Projects/pterosaur/apps/vadmin/auth/utils/login_manage.py", line 14, in <module>
    from .validation import LoginValidation, LoginForm, LoginResult
  File "/Volumes/DATA/Projects/pterosaur/apps/vadmin/auth/utils/validation/__init__.py", line 10, in <module>
    from .login import LoginValidation, LoginForm, LoginResult, WXLoginForm
  File "/Volumes/DATA/Projects/pterosaur/apps/vadmin/auth/utils/validation/login.py", line 13, in <module>
    from apps.vadmin.auth import crud, schemas
  File "/Volumes/DATA/Projects/pterosaur/apps/vadmin/auth/crud.py", line 10, in <module>
    from aioredis import Redis
  File "/Volumes/DATA/Projects/pterosaur/venv/lib/python3.11/site-packages/aioredis/__init__.py", line 1, in <module>
    from aioredis.client import Redis, StrictRedis
  File "/Volumes/DATA/Projects/pterosaur/venv/lib/python3.11/site-packages/aioredis/client.py", line 32, in <module>
    from aioredis.connection import (
  File "/Volumes/DATA/Projects/pterosaur/venv/lib/python3.11/site-packages/aioredis/connection.py", line 33, in <module>
    from .exceptions import (
  File "/Volumes/DATA/Projects/pterosaur/venv/lib/python3.11/site-packages/aioredis/exceptions.py", line 14, in <module>
    class TimeoutError(asyncio.TimeoutError, builtins.TimeoutError, RedisError):
TypeError: duplicate base class TimeoutError

请问是什么原因?

**Comment by vvandk** [comment]
建议退回到Python3.10，这个是因为Python3.11报的错

**Comment by mario654321** [comment]
我的也报错，python 版本3.18
E:/QuantWorkSpaces/kinit/kinit-api/main.py init --env dev
Connected to pydev debugger (build 203.6682.179)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\QuantWorkSpaces\kinit\kinit-api\application\urls.py", line 8, in <module>
    from apps import *
  File "E:\QuantWorkSpaces\kinit\kinit-api\apps\__init__.py", line 10, in <module>
    from apps.vadmin.auth.utils.login import app as auth_app
  File "E:\QuantWorkSpaces\kinit\kinit-api\apps\vadmin\auth\utils\login.py", line 31, in <module>
    from .login_manage import LoginManage
  File "E:\QuantWorkSpaces\kinit\kinit-api\apps\vadmin\auth\utils\login_manage.py", line 14, in <module>
    from .validation import LoginValidation, LoginForm, LoginResult
  File "E:\QuantWorkSpaces\kinit\kinit-api\apps\vadmin\auth\utils\validation\__init__.py", line 9, in <module>
    from .auth import Auth, AuthValidation
  File "E:\QuantWorkSpaces\kinit\kinit-api\apps\vadmin\auth\utils\validation\auth.py", line 27, in <module>
    class AuthValidation:
  File "E:\QuantWorkSpaces\kinit\kinit-api\apps\vadmin\auth\utils\validation\auth.py", line 36, in AuthValidation
    def validate_token(cls, request: Request, token: str | None) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
python-BaseException
请问是什么原因?

**Comment by mario654321** [comment]
只能用Python3.10 吗？

**Comment by vvandk** [comment]
> 

是的，目前3.10以下版本会出现报错问题，3.10以上版本并未测试，所以最好还是用3.10版本来使用此项目

**Comment by vvandk** [comment]
@mario654321 以上报错是因为使用了3.10以下版本，请更新到3.10

**Comment by mario654321** [comment]
禁止传播法轮功反国家、反社会等反动邮件！
禁止传播垃圾邮件！

**Comment by mario654321** [comment]
> 好的收到

**Comment by mario654321** [comment]
禁止传播法轮功反国家、反社会等反动邮件！
禁止传播垃圾邮件！
